version: "3.9"

services:
  db:
    image: postgres:15
    container_name: todo-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - ./Db/server.sql:/docker-entrypoint-initdb.d/server.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d todo_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./API
    container_name: todo-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: todo_db
    ports:
      - "8000:8000"