openapi: 3.0.0
info:
  title: My Go API
  version: 1.0.0
paths:
  /items:
    get:
      operationId: getItems
      responses:
        '200':
          description: OK
servers:
  - url: http://<VM_EXTERNAL_IP>