replicaCount: 1

image:
  repository: gcr.io/cloud-builders/go
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  annotations:
    iam.gke.io/gcp-service-account: api-sa@PROJECT_ID.iam.gserviceaccount.com
  name: api-sa

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

ingress:
  enabled: false
  className: nginx
  host: api.hinivir.xyz

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi


nodeSelector: {}
tolerations: []
affinity: {}
