name: Terraform CI/CD for Dev

on:
  push:
    branches:
    paths:
    - 'infra/**'
    - '.github/workflows/**'
  pull_request:
    paths:
    - 'infra/**'
    - '.github/workflows/**'

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    strategy:
      matrix:
        dir: [ "infra" ]

    permissions:
      contents: read
      pull-requests: write
      id-token: write

    defaults:
      run:
        working-directory: ${{ matrix.dir }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - id: 'auth'
      uses: 'google-github-actions/auth@v3'
      with:
        workload_identity_provider: 'projects/5062636305/locations/global/workloadIdentityPools/github/providers/my-repo'
        service_account: 'github-terraform@g-clo-900.iam.gserviceaccount.com'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.5

    - name: Terraform Init
      run: terraform init -backend-config=backends/dev.config

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -out=tfplan -var-file=dev.tfvars

    - name: Upload Plan
      uses: actions/upload-artifact@v4
      with:
        name: tfplan-${{ matrix.dir }}
        path: ${{ matrix.dir }}/tfplan

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan
    environment: development
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: 'read'
      id-token: 'write'

    strategy:
      matrix:
        dir: [ "infra" ]

    defaults:
      run:
        working-directory: ${{ matrix.dir }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - id: 'auth'
      uses: 'google-github-actions/auth@v3'
      with:
        workload_identity_provider: 'projects/5062636305/locations/global/workloadIdentityPools/github/providers/my-repo'
        service_account: 'github-terraform@g-clo-900.iam.gserviceaccount.com'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.5

    - name: Terraform Init
      run: terraform init -backend-config=backends/dev.config
